// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: msg_types_sc.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace com.bochsler.protocol
{

    [global::ProtoBuf.ProtoContract()]
    public enum SCMessageEnum
    {
        LoginResponse = 10001,
        PingResponse = 10002,
        ReconnectResponse = 10003,
        SCChannelExpired = 10004,
        SCServerClosed = 10005,
        SCServerVersion = 10006,
        SCPrompt = 10007,
        SCNotify = 10008,
        GmOrderResponse = 10009,
        LoginSuccResp = 10010,
        CreateRoleResponse = 10011,
        RoleListResponse = 10012,
        RoleLoginResponse = 10013,
        RoleLogoutResponse = 10014,
        ChatResponse = 10101,
        FaceResponse = 10102,
        DanceResponse = 10103,
        SeatResponse = 10104,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
