// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: msg_types_cs.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace com.bochsler.protocol
{

    [global::ProtoBuf.ProtoContract()]
    public enum CSMessageEnum
    {
        LoginRequest = 10001,
        PingRequest = 10002,
        ReconnectRequest = 10003,
        GmOrderRequest = 10009,
        LoginSuccReq = 10010,
        CreateRoleRequest = 10011,
        RoleListRequest = 10012,
        RoleLoginRequest = 10013,
        RoleLogoutRequest = 10014,
        ChatRequest = 10101,
        FaceRequest = 10102,
        DanceRequest = 10103,
        SeatRequest = 10104,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
