// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: proto_common.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace com.bochsler.protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TestCmdRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cmd", IsRequired = true)]
        public string Cmd { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DisplayAsset : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public DisplayAssetType Type { get; set; } = DisplayAssetType.Resource;

        [global::ProtoBuf.ProtoMember(2, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"num", IsRequired = true)]
        public long Num { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DisplayAssetPackage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"asset")]
        public global::System.Collections.Generic.List<DisplayAsset> Assets { get; } = new global::System.Collections.Generic.List<DisplayAsset>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SpecialDisplayAsset : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public DisplayAssetType Type { get; set; } = DisplayAssetType.Resource;

        [global::ProtoBuf.ProtoMember(2, Name = @"uid", IsRequired = true)]
        public int Uid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"num", IsRequired = true)]
        public long Num { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SpecialDisplayAssetPackage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"specialAsset")]
        public global::System.Collections.Generic.List<SpecialDisplayAsset> specialAssets { get; } = new global::System.Collections.Generic.List<SpecialDisplayAsset>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OkResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IntPair : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key", IsRequired = true)]
        public int Key { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value", IsRequired = true)]
        public int Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Vector3 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x", IsRequired = true)]
        public float X { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"y", IsRequired = true)]
        public float Y { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"z", IsRequired = true)]
        public float Z { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum DisplayAssetType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"RESOURCE")]
        Resource = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ITEM")]
        Item = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"SOLDIER")]
        Soldier = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"COMMANDER")]
        Commander = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"EQUIPMENT")]
        Equipment = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"SKILL_CARD")]
        SkillCard = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"CAR")]
        Car = 7,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum LoginType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"LOGIN_VISITOR")]
        LoginVisitor = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LOGIN_WALLET")]
        LoginWallet = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"LOGIN_ACCOUNT")]
        LoginAccount = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum SceneType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SceneType_NONE")]
        SceneTypeNONE = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"SceneType_MEETING")]
        SceneTypeMEETING = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"SceneType_XINGQIU")]
        SceneTypeXINGQIU = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"SceneType_GALLERY")]
        SceneTypeGALLERY = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"SceneType_LOGIN")]
        SceneTypeLOGIN = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"SceneType_PRIVATE")]
        SceneTypePRIVATE = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"SceneType_GUEST")]
        SceneTypeGUEST = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum RoomType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"RoomType_NONE")]
        RoomTypeNONE = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"RoomType_SYSTEM")]
        RoomTypeSYSTEM = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum PlayerMark
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NORMAL_PLAYER")]
        NormalPlayer = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"GUIDE_PLAYER")]
        GuidePlayer = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"GM")]
        Gm = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"TEST_PLAYER")]
        TestPlayer = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"GUEST")]
        Guest = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OperateType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NORMALLY")]
        Normally = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"IMMEDIATELY")]
        Immediately = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
